###############################################################
#  Generated by:      Cadence Innovus 18.16-s077_1
#  OS:                Linux x86_64(Host ID s2424)
#  Generated on:      Fri Nov 19 23:45:26 2021
#  Design:            counter
#  Command:           create_ccopt_clock_tree_spec -file ccopt_native.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Clocks present at pin clk
#   CLK (period 100.000ns) in timing_config functional_mode([../genus/genus_output/design.sdc])
create_ccopt_clock_tree -name CLK -source clk -no_skew_group

set_ccopt_property source_driver -clock_tree CLK {BUFX2/A BUFX2/Y}
# Clock period setting for source pin of CLK
set_ccopt_property clock_period -pin clk 100

# Skew group to balance non generated clock:CLK in timing_config:functional_mode (sdc ../genus/genus_output/design.sdc)
create_ccopt_skew_group -name CLK/functional_mode -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group CLK/functional_mode true
set_ccopt_property target_insertion_delay -skew_group CLK/functional_mode 0.200
set_ccopt_property extracted_from_clock_name -skew_group CLK/functional_mode CLK
set_ccopt_property extracted_from_constraint_mode_name -skew_group CLK/functional_mode functional_mode
set_ccopt_property extracted_from_delay_corners -skew_group CLK/functional_mode {typ_corner typ_corner}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

